config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root 'dashboard#index'

  get '/missing_purchases', to: 'products#missing_purchases'

  resources :products, :customer_orders, :brands, :franchises

  resources :supplier_orders do
    resources :payments, module: :supplier_orders
  end

  namespace :api do
    namespace :v1 do
      resources :customer_orders
    end
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @products = Product.last(5)
    @supplier_orders = SupplierOrder.last(5)
    @customer_orders = CustomerOrder.last(5)
    @brands = Brand.last(5)
    @franchises = Franchise.last(5)

    @debt = SupplierOrder.debt
    @total_debt = SupplierOrder.total_debt
    @total_rueckstand = Product.total_rueckstand
  end
end

app/views/dashboard/_products.slim
.row
  .col-md-12
    h2
      | Produkte
    table.table.table-striped.table-bordered.shadow
      thead
        tr
          th
            | Produkt
          th
            | Verkauf
          th
            | Einkauf
      tbody
        - @products.each do |product|
          tr
            td= product.full_title
            td
              | 123 Stück
            td
              | $9.99
      tfoot
        tr
          td
            = link_to "New product", new_product_path
            =< link_to "All Products", products_path

app/views/dashboard/index.slim
h1 Dashboard

.container
  .row.mt-4
    .col-md-6
      .card.bg-info.text-white.shadow.mb-4
        .card-body
          h5.card-title
            | Total debt
          p.card-text
            = @total_debt
    .col-md-6
      .card.bg-danger.text-white.shadow.mb-4
        .card-body
          h5.card-title
            | Gesamtrückstand
          p.card-text
            = "#{@total_rueckstand.abs} Figuren"

  .row.mt-4
    h2 Debt per Supplier
    - @debt.each do |supplier, debt|
      .col-md-3
        .card.bg-primary.text-white.shadow.mb-4
          .card-body
            h5.card-title
              = supplier
            p.card-text
              = number_to_currency(debt, unit: "€")

  .row
    .col-md-6
      = render 'customer_orders/table'

    .col-md-6
      = render 'supplier_orders/table'

= render 'products/table'

.card.shadow
  .card-header
    | Brands
  .card-body
    dl.row
      - @brands.each do |brand|
        .col-md-3
          dt= brand.title
  .card-footer
    = link_to "New Brand", new_brand_path, class: 'btn btn-primary'
    =< link_to "All Brands", brands_path, class: 'btn btn-primary'

.card.shadow
  .card-header
    | Franchise
  .card-body
    dl.row
      - @franchises.each do |franchise|
        .col-md-3
          dt= franchise.title
  .card-footer
    = link_to "New Franchise", new_franchise_path, class: 'btn btn-primary'
    =< link_to "All Franchise", franchises_path, class: 'btn btn-primary'