config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root 'dashboard#index'

  get '/missing_purchases', to: 'products#missing_purchases'

  resources :products, :customer_orders, :brands, :franchises

  resources :supplier_orders do
    resources :payments, module: :supplier_orders
  end

  namespace :api do
    namespace :v1 do
      resources :customer_orders
    end
  end
end

app/models/customer_order.rb
class CustomerOrder < ApplicationRecord

  belongs_to :product
  has_many :payments

  def check_coverage
    einkauf = SupplierOrder.where(product_id: product_id).pluck(:amount).sum

    verkauf = self.class.where(product_id: product_id).count

    [einkauf - verkauf, einkauf]
  end
end

app/controllers/api/v1/customer_orders_controller.rb
class Api::V1::CustomerOrdersController < ApplicationController
  protect_from_forgery with: :null_session

  def index
    orders = CustomerOrder.all

    if orders
      render json: {
        status: "SUCCESS",
        message: "Fetched all the orders successfully",
        data: orders
      }, status: :ok
    else
      render json: orders.errors, status: :bad_request
    end
  end

  def create
    Product.find_by_full_title(params[:product_name], params)

    order = CustomerOrder.new(customer_order_params)


    if order.save
      render json: {
        status: "SUCCESS",
        message: "Order was created successfully",
        data: order
      }, status: :created
    else
      render json: order.errors, status: :unprocessable_entity
    end
  end

  private

  def customer_order_params
    params.permit(:product_id, :name, :address, :email, :paid_amount, :state)
  end
end

app/controllers/customer_orders_controller.rb
class CustomerOrdersController < ApplicationController
  def index
    @customer_orders = CustomerOrder.preload(:product).all
  end

  def show
  end

  def new
    @customer_order = CustomerOrder.new
  end

  def create
    @customer_order = CustomerOrder.new(customer_order_params)

    @customer_order.save
  end

  private

  def customer_order_params
    params.require(:customer_order).permit(:product_id, :name, :address, :email, :paid_amount, :state)
  end
end

app/views/customer_orders/_table.slim
.row
  .col-md-12
    h2
      | Verkauf (Kunden)
    table.table.table-striped.shadow.table-info
      thead
        tr
          th
            | Produkt
          th
            | Verbleibend
      tbody
        - @customer_orders.each do |customer_order|
          tr
            td= customer_order.product.full_title
            td
              = customer_order.check_coverage.join(" von ")
      tfoot
        tr
          td colspan="2"
            = link_to "New Customer Order", new_customer_order_path
            =< link_to "All Customer Orders", customer_orders_path

app/views/customer_orders/index.slim
= render 'table'

app/views/customer_orders/new.slim
h2 New Customer Order

dl
  = form_for(@customer_order) do |f|
    dt= f.label :product
    / dd= f.select :product, options_from_collection_for_select(Product.all, :id, :title)
    dd= f.select :product_id, options_for_select(Product.all.map{ |p| [p.full_title, p.id] })

    dt= f.label :name
    dd= f.text_field :name

    dt= f.label :address
    dd= f.text_field :address

    dt= f.label :email
    dd= f.text_field :email

    dt= f.label :state
    dd= f.text_field :state

    dt= f.label :paid_amount
    dd= f.text_field :paid_amount

    dt
    dd= f.submit

app/views/customer_orders/show.html.erb
<h1>CustomerOrders#show</h1>
<p>Find me in app/views/customer_orders/show.html.erb</p>