config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root 'dashboard#index'

  get '/missing_purchases', to: 'products#missing_purchases'

  resources :products, :customer_orders, :brands, :franchises

  resources :supplier_orders do
    resources :payments, module: :supplier_orders
  end

  namespace :api do
    namespace :v1 do
      resources :customer_orders
    end
  end
end

app/views/shared/_navigation.slim
nav.navbar.navbar-expand-lg.bg-dark.navbar-dark
  .container-fluid
    a.navbar-brand[href="#"]
      | Store Manager
    button.navbar-toggler[type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation"]
      span.navbar-toggler-icon
    #navbarScroll.collapse.navbar-collapse
      ul.navbar-nav.me-auto.my-2.my-lg-0.navbar-nav-scroll[style="--bs-scroll-height: 100px;"]
        li.nav-item
          = link_to 'Home', dashboard_index_path, class: 'nav-link'
        li.nav-item.dropdown
          a.nav-link.dropdown-toggle[href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"]
            |  Einkauf (Lieferanten)
          ul.dropdown-menu
            li
              = link_to 'Gesamteinkauf', supplier_orders_path, class: 'dropdown-item'
            li
              = link_to 'Fehlstand', missing_purchases_path, class: 'dropdown-item'
            li
              hr.dropdown-divider
            li
              a.dropdown-item[href="#"]
                | Something else here
        li.nav-item
          = link_to 'Verkauf (Kunden)', customer_orders_path, class: 'nav-link'
        li.nav-item
          = link_to 'Produkte', products_path, class: 'nav-link'
        li.nav-item
          = link_to 'Franchise', franchises_path, class: 'nav-link'

      form.d-flex[role="search"]
        input.form-control.me-2[type="search" placeholder="Search" aria-label="Search"]
        button.btn.btn-outline-success[type="submit"]
          | Search