config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root 'dashboard#index'

  get '/missing_purchases', to: 'products#missing_purchases'

  resources :products, :customer_orders, :brands, :franchises

  resources :supplier_orders do
    resources :payments, module: :supplier_orders
  end

  namespace :api do
    namespace :v1 do
      resources :customer_orders
    end
  end
end

app/models/supplier_order.rb
class SupplierOrder < ApplicationRecord
  include Order

  belongs_to :product
  has_many :payments, as: :payable, dependent: :destroy

  validates :price, :supplier, :amount, presence: true

  accepts_nested_attributes_for :payments, allow_destroy: true

  # @note Schulden pro Hersteller
  def self.debt
    orders = SupplierOrder.preload(:payments).all

    debt = Hash.new(0)

    orders.to_a.group_by(&:supplier).each do |grouped_by, supplier_orders|
      supplier_orders.each do |order|
        einkauf = (order.price * order.amount)
        bezahlt = order.payments.pluck(:amount).sum * order.amount
        debt[grouped_by] += einkauf - bezahlt
      end
    end
    debt
  end

  # @note Gesamtschulden
  def self.total_debt
    debt.values.sum
  end

  # @note Schulden pro Supplier Order
  def debt
    order_einkauf = price * amount

    order_bezahlt = payments.pluck(:amount).sum * amount

    order_einkauf - order_bezahlt
  end
end

app/controllers/supplier_orders/payments_controller.rb
class SupplierOrders::PaymentsController < ApplicationController
  include Payable
  before_action :set_payable

  private

  def set_payable
    @payable = SupplierOrder.find(params[:supplier_order_id])
  end
end

app/controllers/supplier_orders_controller.rb
class SupplierOrdersController < ApplicationController

  before_action :find_supplier_order, only: [:show, :edit, :destroy, :update]

  def index
    @supplier_orders = SupplierOrder.preload(product: [:brand, :franchise]).all
  end

  def show
  end

  def new
    @supplier_order = SupplierOrder.new
    @supplier_order.payments.build
  end

  def edit
  end

  def update
    respond_to do |format|
      if @supplier_order.update(supplier_order_params)
        format.html { redirect_to supplier_order_path(@supplier_order), notice: 'Supplier order was successfully updated'}
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def create
    @supplier_order = SupplierOrder.new(supplier_order_params)

    respond_to do |format|
      if @supplier_order.save
        format.html { redirect_to supplier_order_path(@supplier_order), notice: 'Supplier order was successfully created'}
        format.json { render :show, status: :created, location: @supplier_order }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @supplier_order.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @supplier_order.destroy

    respond_to do |format|
      format.html { redirect_to supplier_orders_path, notice: 'Supplier order was successfully destroyed'}
      format.json { head :no_content }
    end
  end

  private

  def find_supplier_order
    @supplier_order = SupplierOrder.find(params[:id])
  end

  def supplier_order_params
    params.require(:supplier_order).permit(:paid, :price, :product_id, :supplier, :order_number, :amount,
                                            payments_attributes: [:id, :amount, :expense_id, :supplier_order_id, :_destroy])
  end
end

app/views/supplier_orders/_form.slim
- if @supplier_order.errors.any?
  - @supplier_order.errors.full_messages.each do |message|
    = message


= form_for(@supplier_order) do |f|
  dt= f.label :product
  / dd= f.select :product, options_from_collection_for_select(Product.all, :id, :title)
  dd= f.select :product_id, options_for_select(Product.all.map{ |p| [p.full_title, p.id] }), {}, { data: { controller: 'slim' } }

  dt= f.label "Statue price"
  dd= f.number_field :price

  dt= f.label :supplier
  dd= f.select :supplier, ApplicationHelper::SUPPLIERS

  dt= f.label :order_number
  dd= f.text_field :order_number

  dt= f.label "How many were bought?"
  dd= f.text_field :amount

  = f.fields_for :payments do |payment_builder|
    dt= payment_builder.label "What did you pay per statue?"
    dd= payment_builder.number_field :amount

  dt
  dd= f.submit

app/views/supplier_orders/_supplier_order.slim
dt= link_to supplier_order.full_title, supplier_order_path(supplier_order)
dd= link_to "Delete", supplier_order_path(supplier_order), data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'}
dd= link_to edit_supplier_order_path(supplier_order) do
  = fa_icon :pencil

app/views/supplier_orders/_table.slim
.row
  .col-md-12
    h2
      | Einkauf (Lieferanten)
    table.table.table-striped.shadow.table-success
      thead
        tr
          th
          th Produkt
          th Anzahl
          th Preis
          th Bezahlt
          th Noch zu zahlen
      tbody
        - @supplier_orders.each do |supplier_order|
          tr
            td
              = link_to edit_supplier_order_path(supplier_order) do
                = fa_icon :pencil
              =< link_to "Delete", supplier_order_path(supplier_order), data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'}
            td
              = link_to supplier_order.full_title, supplier_order_path(supplier_order)
            td= supplier_order.amount
            td= supplier_order.price.to_s
            td= supplier_order.payments.pluck(:amount).sum
            td= supplier_order.debt
      tfoot
        tr
          td colspan="6"
            = link_to "Neuer Einkauf", new_supplier_order_path
            =< link_to "Alle Einkäufe", supplier_orders_path

app/views/supplier_orders/edit.slim
h2 Edit Supplier Order

dl
  = render 'form'

app/views/supplier_orders/index.slim
= render 'table'

app/views/supplier_orders/new.slim
h2 New Supplier Order

dl
  = render 'form'

app/views/supplier_orders/show.slim
h2= @supplier_order.full_title

.row.mt-4
  .col-md-2
    .card.bg-info.text-white.shadow.mb-4
      .card-body
        h5.card-title
          | Total debt
        p.card-text
          = @supplier_order.debt
  .col-md-2
    .card.bg-primary.text-white.shadow.mb-4
      .card-body
        h5.card-title
          | Debt per Statue
        p.card-text
          = @supplier_order.debt / @supplier_order.amount

dl
  dt Purchase price
  dd= @supplier_order.price

  dt Supplier
  dd= @supplier_order.supplier

  dt Order number
  dd=@supplier_order.order_number

  dt Amount
  dd=@supplier_order.amount

.row
  .col-md-4
    table.table.table-hover
      thead
        tr
          th Paid per statue
          th Paid when
      tbody
        = render @supplier_order.payments

  = render partial: 'payments/form', locals: { payment: Payment.new, payable: @supplier_order }